cadena = input("Intruduce una palabra:")
numero = int(input("Intruduce un numero:"))
decimal = float(input("Intruduce un numero con decimales:"))
print(cadena)
print(numero)
print(decimal)
print(type(cadena))
print(type(numero))
print(type(decimal))